//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaCare.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class klijent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klijent()
        {
            this.racun = new HashSet<racun>();
            this.lijek = new HashSet<lijek>();
        }
    
        public int klijent_id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string kontakt_broj { get; set; }
        public string email_adresa { get; set; }
        public int starost { get; set; }
        public bool clan { get; set; }
        public Nullable<int> bodovi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racun> racun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lijek> lijek { get; set; }
    }
}
