//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaCare.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class lijek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lijek()
        {
            this.stavka_racuna = new HashSet<stavka_racuna>();
            this.klijent = new HashSet<klijent>();
        }
    
        public int lijek_id { get; set; }
        public string naziv { get; set; }
        public decimal cijena__HRK_ { get; set; }
        public string opis { get; set; }
        public int stanje_zaliha { get; set; }
        public System.DateTime rok_uporabe { get; set; }
        public string ime_dobavljaca { get; set; }
        public System.DateTime datum_proizvodnje { get; set; }
        public int proizvodac_id { get; set; }
    
        public virtual proizvodac proizvodac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavka_racuna> stavka_racuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klijent> klijent { get; set; }
    }
}
