//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaCare.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class proizvodac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proizvodac()
        {
            this.lijek = new HashSet<lijek>();
        }
    
        public int proizvodac_id { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string zemlja_porijekla { get; set; }
        public string kontakt_broj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lijek> lijek { get; set; }
    }
}
